bot:
  name: ${GAME_APP_BOT_NAME}
  token: ${GAME_APP_BOT_TOKEN}
spring:
  datasource:
    url: ${GAME_APP_DB_URL}
    username: ${GAME_APP_DB_USERNAME}
    password: ${GAME_APP_DB_PASSWORD}
  flyway:
    schemas:
      - public
      - game_app
  jpa:
    show-sql: true
#  data:
#    redis:
#      host: ${GAME_APP_REDIS_HOST}
#      port: ${GAME_APP_REDIS_PORT}
server:
  port: 8081
logging:
  level:
    sql: info